<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\MmmSdk\MmmSdk.Core\MmmSdk.Core.csproj" />
    <ProjectReference Include="..\..\Plugins\MmmTool.Reminders.Core\MmmTool.Reminders.Core.csproj" />
    <ProjectReference Include="..\..\Shared\MmmTool.Users.Core\MmmTool.Users.Core.csproj" />
  </ItemGroup>

</Project>
