<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MmmTool.Data\MmmTool.Data.csproj" />
    <ProjectReference Include="..\..\..\external\MmmSdk\MmmSdk.Db.SqlServer\MmmSdk.Db.SqlServer.csproj" />
  </ItemGroup>

</Project>
